import { Router, type IRouter } from "express";
import healthRouter from "./health";
import offersRouter from "./offers";
import ordersRouter from "./orders";
import statsRouter from "./stats";
import airportsRouter from "./airports";
import customersRouter from "./customers";
import notesRouter from "./notes";
import ticketsRouter from "./tickets";
import remindersRouter from "./reminders";
import dashboardRouter from "./dashboard";
import authRouter from "./auth";
import employeesRouter from "./employees";

import adminSessionsRouter from "./admin-sessions";
import companiesRouter from "./companies";
import branchesRouter from "./branches";
import settingsRouter from "./settings";
import hrRouter from "./hr";
import reportsRouter from "./reports";
import whatsappRouter from "./whatsapp";
import whatsappCampaignsRouter from "./whatsapp-campaigns";
import supervisorRouter from "./supervisor";
import accountingRouter from "./accounting";
import whatsappRoutingRouter from "./whatsapp_routing.js";
import whatsappAdminRouter from "./whatsapp-admin.js";
import whatsappQuickRepliesRouter from "./whatsapp-quick-replies.js";
import whatsappAutomationsRouter from "./whatsapp-automations.js";
import tiktokRouter from "./tiktok.js";
import tiktokAutomationsRouter from "./tiktok-automations.js";
import notificationsRouter from "./notifications.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(employeesRouter);
router.use(adminSessionsRouter);
router.use(companiesRouter);
router.use(branchesRouter);
router.use(offersRouter);
router.use(ordersRouter);
router.use(statsRouter);
router.use(airportsRouter);
router.use(customersRouter);
router.use(notesRouter);
router.use(ticketsRouter);
router.use(remindersRouter);
router.use(dashboardRouter);
router.use(settingsRouter);
router.use(hrRouter);
router.use(reportsRouter);
router.use(whatsappRouter);
router.use(whatsappCampaignsRouter);
router.use(supervisorRouter);
router.use(accountingRouter);
router.use(whatsappRoutingRouter);
router.use(whatsappAdminRouter);
router.use(whatsappQuickRepliesRouter);
router.use(whatsappAutomationsRouter);
router.use(tiktokRouter);
router.use(tiktokAutomationsRouter);
router.use(notificationsRouter);

export default router;

